label define apptype_codes 1 "ADP", add
label define apptype_codes 2 "ADU", add
label define apptype_codes 3 "ASP", add
label define apptype_codes 4 "CAB", add
label define apptype_codes 5 "CBC", add
label define apptype_codes 6 "CBL", add
label define apptype_codes 7 "CMB", add
label define apptype_codes 8 "CNB", add
label define apptype_codes 9 "CNF", add
label define apptype_codes 10 "CNS", add
label define apptype_codes 11 "CNU", add
label define apptype_codes 12 "CON", add
label define apptype_codes 13 "COT", add
label define apptype_codes 14 "CO1", add
label define apptype_codes 15 "CO2", add
label define apptype_codes 16 "CO3", add
label define apptype_codes 17 "CO4", add
label define apptype_codes 18 "CPE", add
label define apptype_codes 19 "CQ1", add
label define apptype_codes 20 "CQ2", add
label define apptype_codes 21 "CQ3", add
label define apptype_codes 22 "CSK", add
label define apptype_codes 23 "CTN", add
label define apptype_codes 24 "CTY", add
label define apptype_codes 25 "CUS", add
label define apptype_codes 26 "EAL", add
label define apptype_codes 27 "EBA", add
label define apptype_codes 28 "EBF", add
label define apptype_codes 29 "ECL", add
label define apptype_codes 30 "ECU", add
label define apptype_codes 31 "EHK", add
label define apptype_codes 32 "EIB", add
label define apptype_codes 33 "EIC", add
label define apptype_codes 34 "EOL", add
label define apptype_codes 35 "EPS", add
label define apptype_codes 36 "EPU", add
label define apptype_codes 37 "ESE", add
label define apptype_codes 38 "ESU", add
label define apptype_codes 39 "EUN", add
label define apptype_codes 40 "EUS", add
label define apptype_codes 41 "EWA", add
label define apptype_codes 42 "EZZ", add
label define apptype_codes 43 "HOS", add
label define apptype_codes 44 "PAB", add
label define apptype_codes 45 "PBC", add
label define apptype_codes 46 "PCA", add
label define apptype_codes 47 "PMB", add
label define apptype_codes 48 "PNB", add
label define apptype_codes 49 "PNF", add
label define apptype_codes 50 "PNS", add
label define apptype_codes 51 "PON", add
label define apptype_codes 52 "POR", add
label define apptype_codes 53 "PPE", add
label define apptype_codes 54 "PQC", add
label define apptype_codes 55 "PSK", add
label define apptype_codes 56 "PTN", add
label define apptype_codes 57 "PTY", add
label define apptype_codes 58 "PUS", add
label define apptype_codes 59 "SAB", add
label define apptype_codes 60 "SBC", add
label define apptype_codes 61 "SBF", add
label define apptype_codes 62 "SCA", add
label define apptype_codes 63 "SIB", add
label define apptype_codes 64 "SIO", add
label define apptype_codes 65 "SLC", add
label define apptype_codes 66 "SMB", add
label define apptype_codes 67 "SNB", add
label define apptype_codes 68 "SNF", add
label define apptype_codes 69 "SNS", add
label define apptype_codes 70 "SNU", add
label define apptype_codes 71 "SOA", add
label define apptype_codes 72 "SOB", add
label define apptype_codes 73 "SOJ", add
label define apptype_codes 74 "SON", add
label define apptype_codes 75 "SOP", add
label define apptype_codes 76 "SO2", add
label define apptype_codes 77 "SPE", add
label define apptype_codes 78 "SPU", add
label define apptype_codes 79 "SQC", add
label define apptype_codes 80 "SQD", add
label define apptype_codes 81 "SQ4", add
label define apptype_codes 82 "SSK", add
label define apptype_codes 83 "STN", add
label define apptype_codes 84 "STY", add
label define apptype_codes 85 "SUS", add
label define apptype_codes 86 "UAB", add
label define apptype_codes 87 "UBC", add
label define apptype_codes 88 "UCA", add
label define apptype_codes 89 "UMB", add
label define apptype_codes 90 "UNB", add
label define apptype_codes 91 "UNF", add
label define apptype_codes 92 "UNS", add
label define apptype_codes 93 "UON", add
label define apptype_codes 94 "UPE", add
label define apptype_codes 95 "UQC", add
label define apptype_codes 96 "USK", add
label define apptype_codes 97 "USP", add
label define apptype_codes 98 "UTN", add
label define apptype_codes 99 "UTY", add
label define apptype_codes 100 "UUO", add
label define apptype_codes 101 "UUS", add
label define apptype_codes 102 "ZZZ", add

