label define credential_cd_codes 1 "BADM", add
label define credential_cd_codes 2 "BAPA", add
label define credential_cd_codes 3 "BART", add
label define credential_cd_codes 4 "BARV", add
label define credential_cd_codes 5 "BCOM", add
label define credential_cd_codes 6 "BDCA", add
label define credential_cd_codes 7 "BED", add
label define credential_cd_codes 8 "BETH", add
label define credential_cd_codes 9 "BJOUR", add
label define credential_cd_codes 10 "BLSB", add
label define credential_cd_codes 11 "BMSG", add
label define credential_cd_codes 12 "BMUS", add
label define credential_cd_codes 13 "BPAP", add
label define credential_cd_codes 14 "BPEP", add
label define credential_cd_codes 15 "BPHI", add
label define credential_cd_codes 16 "BPSY", add
label define credential_cd_codes 17 "BRLP", add
label define credential_cd_codes 18 "BSCA", add
label define credential_cd_codes 19 "BSCI", add
label define credential_cd_codes 20 "BSCN", add
label define credential_cd_codes 21 "BSMD", add
label define credential_cd_codes 22 "BSNU", add
label define credential_cd_codes 23 "BSSAN", add
label define credential_cd_codes 24 "BSSOC", add
label define credential_cd_codes 25 "BTHEO", add
label define credential_cd_codes 26 "CBREV", add
label define credential_cd_codes 27 "CERA", add
label define credential_cd_codes 28 "CERD", add
label define credential_cd_codes 29 "CERE", add
label define credential_cd_codes 30 "CERG", add
label define credential_cd_codes 31 "CERP", add
label define credential_cd_codes 32 "DIPD", add
label define credential_cd_codes 33 "DIPP", add
label define credential_cd_codes 34 "DLITT", add
label define credential_cd_codes 35 "DMIN", add
label define credential_cd_codes 36 "JD", add
label define credential_cd_codes 37 "LLB", add
label define credential_cd_codes 38 "LLD", add
label define credential_cd_codes 39 "LLET", add
label define credential_cd_codes 40 "LLL", add
label define credential_cd_codes 41 "LLM", add
label define credential_cd_codes 42 "MA", add
label define credential_cd_codes 43 "MAPA", add
label define credential_cd_codes 44 "MARS", add
label define credential_cd_codes 45 "MARV", add
label define credential_cd_codes 46 "MBA", add
label define credential_cd_codes 47 "MBAI", add
label define credential_cd_codes 48 "MCA", add
label define credential_cd_codes 49 "MCMN", add
label define credential_cd_codes 50 "MCS", add
label define credential_cd_codes 51 "MD", add
label define credential_cd_codes 52 "MDCA", add
label define credential_cd_codes 53 "MEBT", add
label define credential_cd_codes 54 "MED", add
label define credential_cd_codes 55 "MENG", add
label define credential_cd_codes 56 "MGEG", add
label define credential_cd_codes 57 "MHA", add
label define credential_cd_codes 58 "MHSC", add
label define credential_cd_codes 59 "MISI", add
label define credential_cd_codes 60 "MLSB", add
label define credential_cd_codes 61 "MMUS", add
label define credential_cd_codes 62 "MPEP", add
label define credential_cd_codes 63 "MPLA", add
label define credential_cd_codes 64 "MPLC", add
label define credential_cd_codes 65 "MPLF", add
label define credential_cd_codes 66 "MPLM", add
label define credential_cd_codes 67 "MPLS", add
label define credential_cd_codes 68 "MPLT", add
label define credential_cd_codes 69 "MPRT", add
label define credential_cd_codes 70 "MPSY", add
label define credential_cd_codes 71 "MREL", add
label define credential_cd_codes 72 "MSC", add
label define credential_cd_codes 73 "MSCA", add
label define credential_cd_codes 74 "MSVS", add
label define credential_cd_codes 75 "MSYS", add
label define credential_cd_codes 76 "MTHEO", add
label define credential_cd_codes 77 "MTRC", add
label define credential_cd_codes 78 "MTRE", add
label define credential_cd_codes 79 "MTRJ", add
label define credential_cd_codes 80 "P", add
label define credential_cd_codes 81 "PHD", add
label define credential_cd_codes 82 "PREU", add
label define credential_cd_codes 83 "QA", add
label define credential_cd_codes 84 "QBA", add
label define credential_cd_codes 85 "QOUAC", add
label define credential_cd_codes 86 "QQD", add
label define credential_cd_codes 87 "QQP", add
label define credential_cd_codes 88 "QQVD", add
label define credential_cd_codes 89 "QQVP", add
label define credential_cd_codes 90 "RES", add

