label define credential_cd_en_abbrev 1 "B.ADMIN.", add
label define credential_cd_en_abbrev 2 "B.H.K.", add
label define credential_cd_en_abbrev 3 "B.A.", add
label define credential_cd_en_abbrev 4 "B.F.A.", add
label define credential_cd_en_abbrev 5 "B.COM.", add
label define credential_cd_en_abbrev 6 "B.C.L.", add
label define credential_cd_en_abbrev 7 "B.ED.", add
label define credential_cd_en_abbrev 8 "B.ETH.", add
label define credential_cd_en_abbrev 9 "B.JOUR.", add
label define credential_cd_en_abbrev 10 "B.L.SC.", add
label define credential_cd_en_abbrev 11 "B.M.SC.", add
label define credential_cd_en_abbrev 12 "B.MUS.", add
label define credential_cd_en_abbrev 13 "B.P.A.", add
label define credential_cd_en_abbrev 14 "B.P.ED.", add
label define credential_cd_en_abbrev 15 "B.PHIL.", add
label define credential_cd_en_abbrev 16 "B.PSY.", add
label define credential_cd_en_abbrev 17 "B.P.REL.", add
label define credential_cd_en_abbrev 18 "B.A.SC.", add
label define credential_cd_en_abbrev 19 "B.SC.", add
label define credential_cd_en_abbrev 20 "B.SC.N.", add
label define credential_cd_en_abbrev 21 "B.MED.SC.", add
label define credential_cd_en_abbrev 22 "B.N.SC.", add
label define credential_cd_en_abbrev 23 "B.H.SC.", add
label define credential_cd_en_abbrev 24 "B.SOC.SC.", add
label define credential_cd_en_abbrev 25 "B.THEO.", add
label define credential_cd_en_abbrev 26 "OTC-TS", add
label define credential_cd_en_abbrev 27 "ADV.CERT.", add
label define credential_cd_en_abbrev 28 "GRAD.CERT.", add
label define credential_cd_en_abbrev 29 "C.ED.-TS", add
label define credential_cd_en_abbrev 30 "GEN.CERT.", add
label define credential_cd_en_abbrev 31 "CERT.", add
label define credential_cd_en_abbrev 32 "G.DIPL.", add
label define credential_cd_en_abbrev 33 "DIPL.", add
label define credential_cd_en_abbrev 34 "D.LETT.", add
label define credential_cd_en_abbrev 35 "D.MIN.", add
label define credential_cd_en_abbrev 36 "J.D.", add
label define credential_cd_en_abbrev 37 "LL.B.", add
label define credential_cd_en_abbrev 38 "LL.D.", add
label define credential_cd_en_abbrev 39 "L.LETT.", add
label define credential_cd_en_abbrev 40 "LL.L", add
label define credential_cd_en_abbrev 41 "LL.M.", add
label define credential_cd_en_abbrev 42 "M.A.", add
label define credential_cd_en_abbrev 43 "M.H.K.", add
label define credential_cd_en_abbrev 44 "M.F.A.", add
label define credential_cd_en_abbrev 45 "M.F.A.", add
label define credential_cd_en_abbrev 46 "M.B.A.", add
label define credential_cd_en_abbrev 47 "I.M.B.A.", add
label define credential_cd_en_abbrev 48 "M.C.A.", add
label define credential_cd_en_abbrev 49 "M.COMM.", add
label define credential_cd_en_abbrev 50 "M.C.S.", add
label define credential_cd_en_abbrev 51 "M.D.", add
label define credential_cd_en_abbrev 52 "M.C.L.", add
label define credential_cd_en_abbrev 53 "M.E.BUS.", add
label define credential_cd_en_abbrev 54 "M.ED.", add
label define credential_cd_en_abbrev 55 "M.ENG.", add
label define credential_cd_en_abbrev 56 "M.GEOG.", add
label define credential_cd_en_abbrev 57 "M.H.A.", add
label define credential_cd_en_abbrev 58 "M.H.SC.", add
label define credential_cd_en_abbrev 59 "M.I.SC.", add
label define credential_cd_en_abbrev 60 "M.L.SC.", add
label define credential_cd_en_abbrev 61 "M.MUS.", add
label define credential_cd_en_abbrev 62 "M.P.ED.", add
label define credential_cd_en_abbrev 63 "M.PLA.", add
label define credential_cd_en_abbrev 64 "MPS-COUNS", add
label define credential_cd_en_abbrev 65 "MPS-FAM.", add
label define credential_cd_en_abbrev 66 "MPS-MAR", add
label define credential_cd_en_abbrev 67 "M.P.S.", add
label define credential_cd_en_abbrev 68 "M.P.THEO.", add
label define credential_cd_en_abbrev 69 "M.F.A.-DIR", add
label define credential_cd_en_abbrev 70 "M.PSY.", add
label define credential_cd_en_abbrev 71 "M.R.ED.", add
label define credential_cd_en_abbrev 72 "M.SC.", add
label define credential_cd_en_abbrev 73 "M.A.SC.", add
label define credential_cd_en_abbrev 74 "M.S.W.", add
label define credential_cd_en_abbrev 75 "M.SYS.SC.", add
label define credential_cd_en_abbrev 76 "M.THEO.", add
label define credential_cd_en_abbrev 77 "M.C.I.", add
label define credential_cd_en_abbrev 78 "M.SP.TRA.", add
label define credential_cd_en_abbrev 79 "M.LEG.TRA.", add
label define credential_cd_en_abbrev 80 "QUAL.MAST.", add
label define credential_cd_en_abbrev 81 "PH.D.", add
label define credential_cd_en_abbrev 82 "PRE.U.", add
label define credential_cd_en_abbrev 83 "A.Q.", add
label define credential_cd_en_abbrev 84 "A.B.Q.", add
label define credential_cd_en_abbrev 85 "QOUAC", add
label define credential_cd_en_abbrev 86 "QQD", add
label define credential_cd_en_abbrev 87 "QQP", add
label define credential_cd_en_abbrev 88 "QQDV", add
label define credential_cd_en_abbrev 89 "QQPV", add
label define credential_cd_en_abbrev 90 "RES", add

