label define credential_cd_fr_abbrev 1 "B.ADM.", add
label define credential_cd_fr_abbrev 2 "B.ACT.PH.", add
label define credential_cd_fr_abbrev 3 "B.A.", add
label define credential_cd_fr_abbrev 4 "B.A.V.", add
label define credential_cd_fr_abbrev 5 "B.COM.", add
label define credential_cd_fr_abbrev 6 "B.D.C.", add
label define credential_cd_fr_abbrev 7 "B.ED.", add
label define credential_cd_fr_abbrev 8 "B.ETH.", add
label define credential_cd_fr_abbrev 9 "B.JOUR.", add
label define credential_cd_fr_abbrev 10 "B.L.SC.", add
label define credential_cd_fr_abbrev 11 "B.M.SC.", add
label define credential_cd_fr_abbrev 12 "B.MUS.", add
label define credential_cd_fr_abbrev 13 "B.A.P.", add
label define credential_cd_fr_abbrev 14 "B.ED.PHYS.", add
label define credential_cd_fr_abbrev 15 "B.PHIL.", add
label define credential_cd_fr_abbrev 16 "B.PS.", add
label define credential_cd_fr_abbrev 17 "B.REL.PUBL", add
label define credential_cd_fr_abbrev 18 "B.SC.A.", add
label define credential_cd_fr_abbrev 19 "B.SC.", add
label define credential_cd_fr_abbrev 20 "B.SC.INF.", add
label define credential_cd_fr_abbrev 21 "B.SC.MÉDIC", add
label define credential_cd_fr_abbrev 22 "B.SC.NUTR.", add
label define credential_cd_fr_abbrev 23 "B.SC.SANTÉ", add
label define credential_cd_fr_abbrev 24 "B.SC.SOC.", add
label define credential_cd_fr_abbrev 25 "B.TH.", add
label define credential_cd_fr_abbrev 26 "B.E.O.É.T.", add
label define credential_cd_fr_abbrev 27 "C.AVANCÉ", add
label define credential_cd_fr_abbrev 28 "C.E.S.", add
label define credential_cd_fr_abbrev 29 "C.ED.-É.T.", add
label define credential_cd_fr_abbrev 30 "C.GÉN.", add
label define credential_cd_fr_abbrev 31 "C.", add
label define credential_cd_fr_abbrev 32 "D.E.S.", add
label define credential_cd_fr_abbrev 33 "DIPL.", add
label define credential_cd_fr_abbrev 34 "D.ÈS L.", add
label define credential_cd_fr_abbrev 35 "D.TH.P.", add
label define credential_cd_fr_abbrev 36 "J.D.", add
label define credential_cd_fr_abbrev 37 "LL.B.", add
label define credential_cd_fr_abbrev 38 "LL.D.", add
label define credential_cd_fr_abbrev 39 "L.ÈS L.", add
label define credential_cd_fr_abbrev 40 "LL.L.", add
label define credential_cd_fr_abbrev 41 "LL.M.", add
label define credential_cd_fr_abbrev 42 "M.A.", add
label define credential_cd_fr_abbrev 43 "M.S.A.P.", add
label define credential_cd_fr_abbrev 44 "M.A.SCÈNE", add
label define credential_cd_fr_abbrev 45 "M.A.V.", add
label define credential_cd_fr_abbrev 46 "M.B.A.", add
label define credential_cd_fr_abbrev 47 "I.M.B.A.", add
label define credential_cd_fr_abbrev 48 "M.C.A.", add
label define credential_cd_fr_abbrev 49 "M.COMM.", add
label define credential_cd_fr_abbrev 50 "M.I.", add
label define credential_cd_fr_abbrev 51 "M.D.", add
label define credential_cd_fr_abbrev 52 "M.D.C.", add
label define credential_cd_fr_abbrev 53 "M.T.A.E.", add
label define credential_cd_fr_abbrev 54 "M.ED.", add
label define credential_cd_fr_abbrev 55 "M.ING.", add
label define credential_cd_fr_abbrev 56 "M.GÉOGR.", add
label define credential_cd_fr_abbrev 57 "M.G.S.S.", add
label define credential_cd_fr_abbrev 58 "M.SC.SAN.", add
label define credential_cd_fr_abbrev 59 "M.S.I.", add
label define credential_cd_fr_abbrev 60 "M.L.SC.", add
label define credential_cd_fr_abbrev 61 "M.MUS.", add
label define credential_cd_fr_abbrev 62 "M.ÉD.PHYS.", add
label define credential_cd_fr_abbrev 63 "M.PLAN.", add
label define credential_cd_fr_abbrev 64 "M.P.COUNS.", add
label define credential_cd_fr_abbrev 65 "M.P.SC.FAM", add
label define credential_cd_fr_abbrev 66 "M.P.CO.MAT", add
label define credential_cd_fr_abbrev 67 "M.P.S.", add
label define credential_cd_fr_abbrev 68 "M.TH.PAST.", add
label define credential_cd_fr_abbrev 69 "M.P.TH.", add
label define credential_cd_fr_abbrev 70 "M.PS.", add
label define credential_cd_fr_abbrev 71 "M.É.R.", add
label define credential_cd_fr_abbrev 72 "M.SC.", add
label define credential_cd_fr_abbrev 73 "M.SC.A.", add
label define credential_cd_fr_abbrev 74 "M.SERV.SOC", add
label define credential_cd_fr_abbrev 75 "M.SYS.", add
label define credential_cd_fr_abbrev 76 "M.TH.", add
label define credential_cd_fr_abbrev 77 "M.I.C.", add
label define credential_cd_fr_abbrev 78 "M.T.E.", add
label define credential_cd_fr_abbrev 79 "M.T.J.", add
label define credential_cd_fr_abbrev 80 "PROP.", add
label define credential_cd_fr_abbrev 81 "PH.D.", add
label define credential_cd_fr_abbrev 82 "PRÉ.U.", add
label define credential_cd_fr_abbrev 83 "Q.A.", add
label define credential_cd_fr_abbrev 84 "Q.B.A.", add
label define credential_cd_fr_abbrev 85 "QOUAC", add
label define credential_cd_fr_abbrev 86 "QQD", add
label define credential_cd_fr_abbrev 87 "QQP", add
label define credential_cd_fr_abbrev 88 "QQDV", add
label define credential_cd_fr_abbrev 89 "QQPV", add
label define credential_cd_fr_abbrev 90 "RES", add

