label define mother_tongue_codes 1 "AAA", add
label define mother_tongue_codes 2 "AAF", add
label define mother_tongue_codes 3 "AAL", add
label define mother_tongue_codes 4 "AAS", add
label define mother_tongue_codes 5 "AAT", add
label define mother_tongue_codes 6 "AAU", add
label define mother_tongue_codes 7 "ABA", add
label define mother_tongue_codes 8 "ACE", add
label define mother_tongue_codes 9 "ADR", add
label define mother_tongue_codes 10 "AGE", add
label define mother_tongue_codes 11 "AII", add
label define mother_tongue_codes 12 "AIR", add
label define mother_tongue_codes 13 "ALA", add
label define mother_tongue_codes 14 "ALD", add
label define mother_tongue_codes 15 "ALG", add
label define mother_tongue_codes 16 "AMH", add
label define mother_tongue_codes 17 "AMP", add
label define mother_tongue_codes 18 "ANC", add
label define mother_tongue_codes 19 "ANG", add
label define mother_tongue_codes 20 "AR", add
label define mother_tongue_codes 21 "ARA", add
label define mother_tongue_codes 22 "ARM", add
label define mother_tongue_codes 23 "ASA", add
label define mother_tongue_codes 24 "ASE", add
label define mother_tongue_codes 25 "ASL", add
label define mother_tongue_codes 26 "AST", add
label define mother_tongue_codes 27 "ATO", add
label define mother_tongue_codes 28 "ATT", add
label define mother_tongue_codes 29 "AUT", add
label define mother_tongue_codes 30 "AWA", add
label define mother_tongue_codes 31 "BEN", add
label define mother_tongue_codes 32 "BIE", add
label define mother_tongue_codes 33 "BUL", add
label define mother_tongue_codes 34 "CHI", add
label define mother_tongue_codes 35 "CHL", add
label define mother_tongue_codes 36 "CHP", add
label define mother_tongue_codes 37 "COR", add
label define mother_tongue_codes 38 "CRE", add
label define mother_tongue_codes 39 "CRI", add
label define mother_tongue_codes 40 "CRO", add
label define mother_tongue_codes 41 "DAK", add
label define mother_tongue_codes 42 "DAN", add
label define mother_tongue_codes 43 "DEN", add
label define mother_tongue_codes 44 "EDN", add
label define mother_tongue_codes 45 "EDS", add
label define mother_tongue_codes 46 "ESP", add
label define mother_tongue_codes 47 "EST", add
label define mother_tongue_codes 48 "FDC", add
label define mother_tongue_codes 49 "FIN", add
label define mother_tongue_codes 50 "FLA", add
label define mother_tongue_codes 51 "FRA", add
label define mother_tongue_codes 52 "FRI", add
label define mother_tongue_codes 53 "GAL", add
label define mother_tongue_codes 54 "GIT", add
label define mother_tongue_codes 55 "GRE", add
label define mother_tongue_codes 56 "GUJ", add
label define mother_tongue_codes 57 "HAI", add
label define mother_tongue_codes 58 "HEB", add
label define mother_tongue_codes 59 "HON", add
label define mother_tongue_codes 60 "IND", add
label define mother_tongue_codes 61 "INU", add
label define mother_tongue_codes 62 "ISL", add
label define mother_tongue_codes 63 "ITA", add
label define mother_tongue_codes 64 "JAP", add
label define mother_tongue_codes 65 "KAN", add
label define mother_tongue_codes 66 "KGI", add
label define mother_tongue_codes 67 "KHM", add
label define mother_tongue_codes 68 "KON", add
label define mother_tongue_codes 69 "KUR", add
label define mother_tongue_codes 70 "KUT", add
label define mother_tongue_codes 71 "LAO", add
label define mother_tongue_codes 72 "LET", add
label define mother_tongue_codes 73 "LGA", add
label define mother_tongue_codes 74 "LIT", add
label define mother_tongue_codes 75 "MAB", add
label define mother_tongue_codes 76 "MAC", add
label define mother_tongue_codes 77 "MAL", add
label define mother_tongue_codes 78 "MAR", add
label define mother_tongue_codes 79 "MIC", add
label define mother_tongue_codes 80 "MLC", add
label define mother_tongue_codes 81 "MLT", add
label define mother_tongue_codes 82 "MOH", add
label define mother_tongue_codes 83 "MON", add
label define mother_tongue_codes 84 "NEE", add
label define mother_tongue_codes 85 "NIS", add
label define mother_tongue_codes 86 "NOO", add
label define mother_tongue_codes 87 "NOR", add
label define mother_tongue_codes 88 "OJC", add
label define mother_tongue_codes 89 "OJI", add
label define mother_tongue_codes 90 "OUR", add
label define mother_tongue_codes 91 "PAC", add
label define mother_tongue_codes 92 "PEN", add
label define mother_tongue_codes 93 "PER", add
label define mother_tongue_codes 94 "PIE", add
label define mother_tongue_codes 95 "POL", add
label define mother_tongue_codes 96 "POR", add
label define mother_tongue_codes 97 "POT", add
label define mother_tongue_codes 98 "ROU", add
label define mother_tongue_codes 99 "RUS", add
label define mother_tongue_codes 100 "SEC", add
label define mother_tongue_codes 101 "SER", add
label define mother_tongue_codes 102 "SHU", add
label define mother_tongue_codes 103 "SID", add
label define mother_tongue_codes 104 "SIN", add
label define mother_tongue_codes 105 "SLO", add
label define mother_tongue_codes 106 "SLV", add
label define mother_tongue_codes 107 "SOM", add
label define mother_tongue_codes 108 "SUE", add
label define mother_tongue_codes 109 "SWA", add
label define mother_tongue_codes 110 "TAG", add
label define mother_tongue_codes 111 "TAM", add
label define mother_tongue_codes 112 "TCH", add
label define mother_tongue_codes 113 "TEL", add
label define mother_tongue_codes 114 "THA", add
label define mother_tongue_codes 115 "THO", add
label define mother_tongue_codes 116 "TIG", add
label define mother_tongue_codes 117 "TLI", add
label define mother_tongue_codes 118 "TSI", add
label define mother_tongue_codes 119 "TUR", add
label define mother_tongue_codes 120 "TWI", add
label define mother_tongue_codes 121 "UKR", add
label define mother_tongue_codes 122 "VIE", add
label define mother_tongue_codes 123 "YID", add

