label define subject_cd_codes 1 "AAC", add
label define subject_cd_codes 2 "ADA", add
label define subject_cd_codes 3 "ADC", add
label define subject_cd_codes 4 "ADE", add
label define subject_cd_codes 5 "ADG", add
label define subject_cd_codes 6 "ADM", add
label define subject_cd_codes 7 "ADR", add
label define subject_cd_codes 8 "AED", add
label define subject_cd_codes 9 "AEF", add
label define subject_cd_codes 10 "AER", add
label define subject_cd_codes 11 "AGI", add
label define subject_cd_codes 12 "AIN", add
label define subject_cd_codes 13 "AIT", add
label define subject_cd_codes 14 "AJV", add
label define subject_cd_codes 15 "ALF", add
label define subject_cd_codes 16 "ALG", add
label define subject_cd_codes 17 "ALS", add
label define subject_cd_codes 18 "AMM", add
label define subject_cd_codes 19 "ANA", add
label define subject_cd_codes 20 "ANG", add
label define subject_cd_codes 21 "ANG", add
label define subject_cd_codes 22 "ANI", add
label define subject_cd_codes 23 "ANT", add
label define subject_cd_codes 24 "APA", add
label define subject_cd_codes 25 "APL", add
label define subject_cd_codes 26 "APN", add
label define subject_cd_codes 27 "ARB", add
label define subject_cd_codes 28 "ARC", add
label define subject_cd_codes 29 "ARG", add
label define subject_cd_codes 30 "ARI", add
label define subject_cd_codes 31 "ARR", add
label define subject_cd_codes 32 "ARR", add
label define subject_cd_codes 33 "ART", add
label define subject_cd_codes 34 "ARV", add
label define subject_cd_codes 35 "ARV", add
label define subject_cd_codes 36 "ASI", add
label define subject_cd_codes 37 "AST", add
label define subject_cd_codes 38 "ATE", add
label define subject_cd_codes 39 "ATM", add
label define subject_cd_codes 40 "AUD", add
label define subject_cd_codes 41 "AVB", add
label define subject_cd_codes 42 "BCH", add
label define subject_cd_codes 43 "BIM", add
label define subject_cd_codes 44 "BIO", add
label define subject_cd_codes 45 "BIO", add
label define subject_cd_codes 46 "BMG", add
label define subject_cd_codes 47 "BNF", add
label define subject_cd_codes 48 "BPS", add
label define subject_cd_codes 49 "BST", add
label define subject_cd_codes 50 "BUS", add
label define subject_cd_codes 51 "CAT", add
label define subject_cd_codes 52 "CCI", add
label define subject_cd_codes 53 "CCL", add
label define subject_cd_codes 54 "CDN", add
label define subject_cd_codes 55 "CDN", add
label define subject_cd_codes 56 "CEC", add
label define subject_cd_codes 57 "CEG", add
label define subject_cd_codes 58 "CEN", add
label define subject_cd_codes 59 "CGD", add
label define subject_cd_codes 60 "CGR", add
label define subject_cd_codes 61 "CGS", add
label define subject_cd_codes 62 "CHC", add
label define subject_cd_codes 63 "CHE", add
label define subject_cd_codes 64 "CHG", add
label define subject_cd_codes 65 "CHM", add
label define subject_cd_codes 66 "CHM", add
label define subject_cd_codes 67 "CHO", add
label define subject_cd_codes 68 "CHO", add
label define subject_cd_codes 69 "CHP", add
label define subject_cd_codes 70 "CHR", add
label define subject_cd_codes 71 "CHT", add
label define subject_cd_codes 72 "CII", add
label define subject_cd_codes 73 "CIN", add
label define subject_cd_codes 74 "CLA", add
label define subject_cd_codes 75 "CLT", add
label define subject_cd_codes 76 "CMG", add
label define subject_cd_codes 77 "CML", add
label define subject_cd_codes 78 "CMM", add
label define subject_cd_codes 79 "CMN", add
label define subject_cd_codes 80 "CMR", add
label define subject_cd_codes 81 "CMS", add
label define subject_cd_codes 82 "CMT", add
label define subject_cd_codes 83 "CNF", add
label define subject_cd_codes 84 "COC", add
label define subject_cd_codes 85 "COE", add
label define subject_cd_codes 86 "COG", add
label define subject_cd_codes 87 "COI", add
label define subject_cd_codes 88 "COM", add
label define subject_cd_codes 89 "COM", add
label define subject_cd_codes 90 "COO", add
label define subject_cd_codes 91 "COS", add
label define subject_cd_codes 92 "COT", add
label define subject_cd_codes 93 "CPT", add
label define subject_cd_codes 94 "CRM", add
label define subject_cd_codes 95 "CRS", add
label define subject_cd_codes 96 "CSD", add
label define subject_cd_codes 97 "CSE", add
label define subject_cd_codes 98 "CSE", add
label define subject_cd_codes 99 "CSI", add
label define subject_cd_codes 100 "CSS", add
label define subject_cd_codes 101 "CTA", add
label define subject_cd_codes 102 "CTC", add
label define subject_cd_codes 103 "CTI", add
label define subject_cd_codes 104 "CVG", add
label define subject_cd_codes 105 "DAD", add
label define subject_cd_codes 106 "DAN", add
label define subject_cd_codes 107 "DCA", add
label define subject_cd_codes 108 "DCL", add
label define subject_cd_codes 109 "DCL", add
label define subject_cd_codes 110 "DCT", add
label define subject_cd_codes 111 "DED", add
label define subject_cd_codes 112 "DEV", add
label define subject_cd_codes 113 "DHS", add
label define subject_cd_codes 114 "DID", add
label define subject_cd_codes 115 "DIG", add
label define subject_cd_codes 116 "DIN", add
label define subject_cd_codes 117 "DJS", add
label define subject_cd_codes 118 "DLA", add
label define subject_cd_codes 119 "DLE", add
label define subject_cd_codes 120 "DLF", add
label define subject_cd_codes 121 "DLS", add
label define subject_cd_codes 122 "DLS", add
label define subject_cd_codes 123 "DLS", add
label define subject_cd_codes 124 "DPR", add
label define subject_cd_codes 125 "DPU", add
label define subject_cd_codes 126 "DRC", add
label define subject_cd_codes 127 "DSC", add
label define subject_cd_codes 128 "DTC", add
label define subject_cd_codes 129 "DVM", add
label define subject_cd_codes 130 "EAE", add
label define subject_cd_codes 131 "EAG", add
label define subject_cd_codes 132 "EAL", add
label define subject_cd_codes 133 "EAU", add
label define subject_cd_codes 134 "EAV", add
label define subject_cd_codes 135 "EBB", add
label define subject_cd_codes 136 "EBB", add
label define subject_cd_codes 137 "EBC", add
label define subject_cd_codes 138 "EBI", add
label define subject_cd_codes 139 "EBT", add
label define subject_cd_codes 140 "ECD", add
label define subject_cd_codes 141 "ECH", add
label define subject_cd_codes 142 "ECI", add
label define subject_cd_codes 143 "ECM", add
label define subject_cd_codes 144 "ECO", add
label define subject_cd_codes 145 "ECP", add
label define subject_cd_codes 146 "ECS", add
label define subject_cd_codes 147 "EDB", add
label define subject_cd_codes 148 "EDD", add
label define subject_cd_codes 149 "EDE", add
label define subject_cd_codes 150 "EDF", add
label define subject_cd_codes 151 "EDU", add
label define subject_cd_codes 152 "EDV", add
label define subject_cd_codes 153 "EED", add
label define subject_cd_codes 154 "EES", add
label define subject_cd_codes 155 "EEU", add
label define subject_cd_codes 156 "EEZ", add
label define subject_cd_codes 157 "EFA", add
label define subject_cd_codes 158 "EFL", add
label define subject_cd_codes 159 "EFO", add
label define subject_cd_codes 160 "EFP", add
label define subject_cd_codes 161 "EFR", add
label define subject_cd_codes 162 "EIL", add
label define subject_cd_codes 163 "ELA", add
label define subject_cd_codes 164 "ELC", add
label define subject_cd_codes 165 "ELF", add
label define subject_cd_codes 166 "ELG", add
label define subject_cd_codes 167 "ELI", add
label define subject_cd_codes 168 "ELO", add
label define subject_cd_codes 169 "EMA", add
label define subject_cd_codes 170 "EMP", add
label define subject_cd_codes 171 "ENA", add
label define subject_cd_codes 172 "ENF", add
label define subject_cd_codes 173 "ENG", add
label define subject_cd_codes 174 "ENG", add
label define subject_cd_codes 175 "ENL", add
label define subject_cd_codes 176 "ENR", add
label define subject_cd_codes 177 "ENT", add
label define subject_cd_codes 178 "ENT", add
label define subject_cd_codes 179 "ENV", add
label define subject_cd_codes 180 "EPE", add
label define subject_cd_codes 181 "EPH", add
label define subject_cd_codes 182 "EPH", add
label define subject_cd_codes 183 "EPI", add
label define subject_cd_codes 184 "EPP", add
label define subject_cd_codes 185 "EPR", add
label define subject_cd_codes 186 "EPS", add
label define subject_cd_codes 187 "EPT", add
label define subject_cd_codes 188 "EPT", add
label define subject_cd_codes 189 "ERG", add
label define subject_cd_codes 190 "ESC", add
label define subject_cd_codes 191 "ESD", add
label define subject_cd_codes 192 "ESL", add
label define subject_cd_codes 193 "ESL", add
label define subject_cd_codes 194 "ESM", add
label define subject_cd_codes 195 "ESP", add
label define subject_cd_codes 196 "ESP", add
label define subject_cd_codes 197 "EST", add
label define subject_cd_codes 198 "ETA", add
label define subject_cd_codes 199 "ETH", add
label define subject_cd_codes 200 "ETJ", add
label define subject_cd_codes 201 "ETQ", add
label define subject_cd_codes 202 "ETS", add
label define subject_cd_codes 203 "ETX", add
label define subject_cd_codes 204 "EVG", add
label define subject_cd_codes 205 "EVG", add
label define subject_cd_codes 206 "EVS", add
label define subject_cd_codes 207 "FDR", add
label define subject_cd_codes 208 "FDT", add
label define subject_cd_codes 209 "FEM", add
label define subject_cd_codes 210 "FEM", add
label define subject_cd_codes 211 "FIN", add
label define subject_cd_codes 212 "FLM", add
label define subject_cd_codes 213 "FLS", add
label define subject_cd_codes 214 "FLS", add
label define subject_cd_codes 215 "FMU", add
label define subject_cd_codes 216 "FRA", add
label define subject_cd_codes 217 "FRA", add
label define subject_cd_codes 218 "FRE", add
label define subject_cd_codes 219 "FRS", add
label define subject_cd_codes 220 "FTE", add
label define subject_cd_codes 221 "FVI", add
label define subject_cd_codes 222 "GAS", add
label define subject_cd_codes 223 "GDS", add
label define subject_cd_codes 224 "GEG", add
label define subject_cd_codes 225 "GEG", add
label define subject_cd_codes 226 "GEI", add
label define subject_cd_codes 227 "GEN", add
label define subject_cd_codes 228 "GEN", add
label define subject_cd_codes 229 "GEO", add
label define subject_cd_codes 230 "GER", add
label define subject_cd_codes 231 "GIN", add
label define subject_cd_codes 232 "GMD", add
label define subject_cd_codes 233 "GNG", add
label define subject_cd_codes 234 "GPH", add
label define subject_cd_codes 235 "GPP", add
label define subject_cd_codes 236 "GPY", add
label define subject_cd_codes 237 "GRA", add
label define subject_cd_codes 238 "GRE", add
label define subject_cd_codes 239 "GRH", add
label define subject_cd_codes 240 "GRN", add
label define subject_cd_codes 241 "GRR", add
label define subject_cd_codes 242 "GRT", add
label define subject_cd_codes 243 "HAH", add
label define subject_cd_codes 244 "HAR", add
label define subject_cd_codes 245 "HCA", add
label define subject_cd_codes 246 "HCS", add
label define subject_cd_codes 247 "HIS", add
label define subject_cd_codes 248 "HIS", add
label define subject_cd_codes 249 "HMG", add
label define subject_cd_codes 250 "HOR", add
label define subject_cd_codes 251 "HOT", add
label define subject_cd_codes 252 "HSA", add
label define subject_cd_codes 253 "HSR", add
label define subject_cd_codes 254 "HSR", add
label define subject_cd_codes 255 "HSS", add
label define subject_cd_codes 256 "HST", add
label define subject_cd_codes 257 "HTA", add
label define subject_cd_codes 258 "HTA", add
label define subject_cd_codes 259 "ICS", add
label define subject_cd_codes 260 "INE", add
label define subject_cd_codes 261 "INF", add
label define subject_cd_codes 262 "INN", add
label define subject_cd_codes 263 "INT", add
label define subject_cd_codes 264 "IPA", add
label define subject_cd_codes 265 "ISC", add
label define subject_cd_codes 266 "ISI", add
label define subject_cd_codes 267 "ITA", add
label define subject_cd_codes 268 "ITC", add
label define subject_cd_codes 269 "IVA", add
label define subject_cd_codes 270 "IVC", add
label define subject_cd_codes 271 "IVS", add
label define subject_cd_codes 272 "JOU", add
label define subject_cd_codes 273 "KIN", add
label define subject_cd_codes 274 "LAF", add
label define subject_cd_codes 275 "LAT", add
label define subject_cd_codes 276 "LCE", add
label define subject_cd_codes 277 "LCL", add
label define subject_cd_codes 278 "LDE", add
label define subject_cd_codes 279 "LDR", add
label define subject_cd_codes 280 "LEC", add
label define subject_cd_codes 281 "LEG", add
label define subject_cd_codes 282 "LIA", add
label define subject_cd_codes 283 "LIF", add
label define subject_cd_codes 284 "LIN", add
label define subject_cd_codes 285 "LLF", add
label define subject_cd_codes 286 "LLR", add
label define subject_cd_codes 287 "LSB", add
label define subject_cd_codes 288 "LSB", add
label define subject_cd_codes 289 "LSR", add
label define subject_cd_codes 290 "LSS", add
label define subject_cd_codes 291 "LTE", add
label define subject_cd_codes 292 "LTF", add
label define subject_cd_codes 293 "MAE", add
label define subject_cd_codes 294 "MAF", add
label define subject_cd_codes 295 "MAN", add
label define subject_cd_codes 296 "MAS", add
label define subject_cd_codes 297 "MAT", add
label define subject_cd_codes 298 "MAT", add
label define subject_cd_codes 299 "MCA", add
label define subject_cd_codes 300 "MCG", add
label define subject_cd_codes 301 "MDE", add
label define subject_cd_codes 302 "MDG", add
label define subject_cd_codes 303 "MDN", add
label define subject_cd_codes 304 "MDR", add
label define subject_cd_codes 305 "MDV", add
label define subject_cd_codes 306 "MED", add
label define subject_cd_codes 307 "MEE", add
label define subject_cd_codes 308 "MEV", add
label define subject_cd_codes 309 "MEX", add
label define subject_cd_codes 310 "MGB", add
label define subject_cd_codes 311 "MGT", add
label define subject_cd_codes 312 "MHS", add
label define subject_cd_codes 313 "MIC", add
label define subject_cd_codes 314 "MII", add
label define subject_cd_codes 315 "MIS", add
label define subject_cd_codes 316 "MKT", add
label define subject_cd_codes 317 "MOR", add
label define subject_cd_codes 318 "MPI", add
label define subject_cd_codes 319 "MPP", add
label define subject_cd_codes 320 "MSG", add
label define subject_cd_codes 321 "MUE", add
label define subject_cd_codes 322 "MUI", add
label define subject_cd_codes 323 "MUS", add
label define subject_cd_codes 324 "MUV", add
label define subject_cd_codes 325 "NAT", add
label define subject_cd_codes 326 "NEC", add
label define subject_cd_codes 327 "NEU", add
label define subject_cd_codes 328 "NOS", add
label define subject_cd_codes 329 "NOT", add
label define subject_cd_codes 330 "NOT", add
label define subject_cd_codes 331 "NSC", add
label define subject_cd_codes 332 "NSC", add
label define subject_cd_codes 333 "NSG", add
label define subject_cd_codes 334 "NSH", add
label define subject_cd_codes 335 "NSP", add
label define subject_cd_codes 336 "NUT", add
label define subject_cd_codes 337 "OCC", add
label define subject_cd_codes 338 "OMT", add
label define subject_cd_codes 339 "ORA", add
label define subject_cd_codes 340 "ORD", add
label define subject_cd_codes 341 "ORO", add
label define subject_cd_codes 342 "ORS", add
label define subject_cd_codes 343 "PAG", add
label define subject_cd_codes 344 "PAL", add
label define subject_cd_codes 345 "PAP", add
label define subject_cd_codes 346 "PAT", add
label define subject_cd_codes 347 "PCA", add
label define subject_cd_codes 348 "PCC", add
label define subject_cd_codes 349 "PCH", add
label define subject_cd_codes 350 "PCL", add
label define subject_cd_codes 351 "PCO", add
label define subject_cd_codes 352 "PCP", add
label define subject_cd_codes 353 "PCQ", add
label define subject_cd_codes 354 "PCT", add
label define subject_cd_codes 355 "PED", add
label define subject_cd_codes 356 "PEP", add
label define subject_cd_codes 357 "PGE", add
label define subject_cd_codes 358 "PHA", add
label define subject_cd_codes 359 "PHC", add
label define subject_cd_codes 360 "PHI", add
label define subject_cd_codes 361 "PHN", add
label define subject_cd_codes 362 "PHO", add
label define subject_cd_codes 363 "PHO", add
label define subject_cd_codes 364 "PHR", add
label define subject_cd_codes 365 "PHS", add
label define subject_cd_codes 366 "PHT", add
label define subject_cd_codes 367 "PHY", add
label define subject_cd_codes 368 "PHY", add
label define subject_cd_codes 369 "PIC", add
label define subject_cd_codes 370 "PIN", add
label define subject_cd_codes 371 "PLA", add
label define subject_cd_codes 372 "PLB", add
label define subject_cd_codes 373 "PLC", add
label define subject_cd_codes 374 "PLF", add
label define subject_cd_codes 375 "PLS", add
label define subject_cd_codes 376 "PLT", add
label define subject_cd_codes 377 "PMA", add
label define subject_cd_codes 378 "PMD", add
label define subject_cd_codes 379 "PMG", add
label define subject_cd_codes 380 "PNP", add
label define subject_cd_codes 381 "POL", add
label define subject_cd_codes 382 "POP", add
label define subject_cd_codes 383 "PPM", add
label define subject_cd_codes 384 "PPT", add
label define subject_cd_codes 385 "PPU", add
label define subject_cd_codes 386 "PRA", add
label define subject_cd_codes 387 "PSC", add
label define subject_cd_codes 388 "PSG", add
label define subject_cd_codes 389 "PSP", add
label define subject_cd_codes 390 "PSP", add
label define subject_cd_codes 391 "PSS", add
label define subject_cd_codes 392 "PSY", add
label define subject_cd_codes 393 "PTI", add
label define subject_cd_codes 394 "RAE", add
label define subject_cd_codes 395 "RDS", add
label define subject_cd_codes 396 "REA", add
label define subject_cd_codes 397 "REC", add
label define subject_cd_codes 398 "REL", add
label define subject_cd_codes 399 "REL", add
label define subject_cd_codes 400 "RFA", add
label define subject_cd_codes 401 "RHS", add
label define subject_cd_codes 402 "RIP", add
label define subject_cd_codes 403 "RLG", add
label define subject_cd_codes 404 "RLP", add
label define subject_cd_codes 405 "RMB", add
label define subject_cd_codes 406 "RPC", add
label define subject_cd_codes 407 "RPD", add
label define subject_cd_codes 408 "RPE", add
label define subject_cd_codes 409 "RPL", add
label define subject_cd_codes 410 "RUS", add
label define subject_cd_codes 411 "RVG", add
label define subject_cd_codes 412 "SCG", add
label define subject_cd_codes 413 "SCI", add
label define subject_cd_codes 414 "SCI", add
label define subject_cd_codes 415 "SCL", add
label define subject_cd_codes 416 "SCS", add
label define subject_cd_codes 417 "SDC", add
label define subject_cd_codes 418 "SDT", add
label define subject_cd_codes 419 "SED", add
label define subject_cd_codes 420 "SEG", add
label define subject_cd_codes 421 "SEG", add
label define subject_cd_codes 422 "SHP", add
label define subject_cd_codes 423 "SHS", add
label define subject_cd_codes 424 "SIG", add
label define subject_cd_codes 425 "SLV", add
label define subject_cd_codes 426 "SOC", add
label define subject_cd_codes 427 "SOP", add
label define subject_cd_codes 428 "SPI", add
label define subject_cd_codes 429 "SPR", add
label define subject_cd_codes 430 "SPT", add
label define subject_cd_codes 431 "SRD", add
label define subject_cd_codes 432 "SRS", add
label define subject_cd_codes 433 "SRS", add
label define subject_cd_codes 434 "SSA", add
label define subject_cd_codes 435 "SSC", add
label define subject_cd_codes 436 "SSE", add
label define subject_cd_codes 437 "SSM", add
label define subject_cd_codes 438 "SSO", add
label define subject_cd_codes 439 "SSP", add
label define subject_cd_codes 440 "SSS", add
label define subject_cd_codes 441 "STA", add
label define subject_cd_codes 442 "STS", add
label define subject_cd_codes 443 "STT", add
label define subject_cd_codes 444 "SVS", add
label define subject_cd_codes 445 "SYC", add
label define subject_cd_codes 446 "SYS", add
label define subject_cd_codes 447 "TCC", add
label define subject_cd_codes 448 "TCF", add
label define subject_cd_codes 449 "TCI", add
label define subject_cd_codes 450 "TCO", add
label define subject_cd_codes 451 "TCR", add
label define subject_cd_codes 452 "TCS", add
label define subject_cd_codes 453 "TCT", add
label define subject_cd_codes 454 "TER", add
label define subject_cd_codes 455 "TES", add
label define subject_cd_codes 456 "THA", add
label define subject_cd_codes 457 "THC", add
label define subject_cd_codes 458 "THE", add
label define subject_cd_codes 459 "THF", add
label define subject_cd_codes 460 "THI", add
label define subject_cd_codes 461 "THO", add
label define subject_cd_codes 462 "TIN", add
label define subject_cd_codes 463 "TLG", add
label define subject_cd_codes 464 "TOL", add
label define subject_cd_codes 465 "TOX", add
label define subject_cd_codes 466 "TPA", add
label define subject_cd_codes 467 "TPH", add
label define subject_cd_codes 468 "TPR", add
label define subject_cd_codes 469 "TRA", add
label define subject_cd_codes 470 "TRD", add
label define subject_cd_codes 471 "TRE", add
label define subject_cd_codes 472 "TRI", add
label define subject_cd_codes 473 "TRJ", add
label define subject_cd_codes 474 "TRS", add
label define subject_cd_codes 475 "TSE", add
label define subject_cd_codes 476 "TSH", add
label define subject_cd_codes 477 "TXV", add
label define subject_cd_codes 478 "UPR", add
label define subject_cd_codes 479 "VCC", add
label define subject_cd_codes 480 "VCN", add
label define subject_cd_codes 481 "VIE", add
label define subject_cd_codes 482 "VOC", add
label define subject_cd_codes 483 "ZZB", add
label define subject_cd_codes 484 "ZZI", add

